### ISSUE TITLE
Previously selected notes remain selected when pasting

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamalfalfa#114]
[Screen Recording 2019-05-08 at 10.58.51 AM.zip](https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamalfalfa/files/3158725/Screen.Recording.2019-05-08.at.10.58.51.AM.zip)

**Comment by jamesbgd** [comment]
Cannot duplicate.
